Class {
	#name : #MultVictimBox,
	#superclass : #Object,
	#category : #'IngSoft2-Model'
}

{ #category : #'as yet unclassified' }
MultVictimBox >> affect: somePLayers [
	^[].
]

{ #category : #'as yet unclassified' }
MultVictimBox >> affect: somePLayers and: aBoard [
	^[].
]

{ #category : #'as yet unclassified' }
MultVictimBox >> applyOver: positions triggeredOn: aPosition with: sizeOfBoard [
	^[].
]
